# Generated by Django 2.2.5 on 2020-02-28 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20200228_1759'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amentiny',
            new_name='Amenity',
        ),
    ]
